### ISSUE TITLE
Exe not launching

### ISSUE THREAD

**Issue by Pixel-Meister** [crossfire151/Fable-III-Patcher#1]
Double-clicking the Fable.III.Patcher doesn't open a window. I have the resources folder with the .dll and .zip in the same directory as the .exe.

**Comment by crossfire151** [comment]
Hi,

You need to unzip the zip file with all the files in a single folder named "resources", this folder must on contain the files inside the zip file and nothing else, no other folders just the files.

After you done this it will work as intended.

**Comment by crossfire151** [comment]
Please take a look at the new [README](https://github.com/crossfire151/Fable-III-Patcher/blob/master/README.md), if this doesn't help much let me know and I will see what other steps we can take.

**Comment by Curadusk** [comment]
I was having the same issue as the above user. I did not get any error messages. The downloaded files had different filenames, so I had to rename the files (replacing . with space)
Fable.III.Patcher.exe -> Fable III Patcher.exe
MetroSet.UI.dll -> MetroSet UI.dll

**Comment by crossfire151** [comment]
I will do some debugging and see if I can figure out what's causing these issues.
I should have a updated release within the hour that should hopefully resolve your issues.

**Comment by crossfire151** [comment]
I have created a Discord Support server to best help with support issues: [https://discord.gg/nQRsMxZ3Ha](https://discord.gg/nQRsMxZ3Ha)

**Comment by Pixel-Meister** [comment]
@Curadusk That fixed it, thanks! Crossfire, appreciate the rapid debugging.
